version: '2'
networks:
  default:
    external:
      name: ggggg
services:
  php:
    build: .
    image: phplci:70
    privileged: false
    restart: unless-stopped
    tty: true
    volumes: 
      - .:/var/www/html
  php71:
    build: 
      context: .
      dockerfile: Dockerfile71
    image: phplci:71
    privileged: false
    restart: unless-stopped
    tty: true
    volumes: 
      - .:/var/www/html
  php72:
    build: 
      context: .
      dockerfile: Dockerfile72
    image: phplci:71
    privileged: false
    restart: unless-stopped
    tty: true
    volumes: 
      - .:/var/www/html